# Generated by Django 4.1.7 on 2023-03-26 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('moving', models.BooleanField(default=False)),
                ('currentFloor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentFloorFloorModel', to='floor.floormodel')),
                ('requestList', models.ManyToManyField(related_name='requestListFloorModel', to='floor.floormodel')),
            ],
        ),
    ]
