# Generated by Django 4.1.7 on 2023-03-27 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0001_initial'),
        ('elevator', '0002_alter_elevatormodel_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevatormodel',
            name='currentFloor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentFloorFloorModel', to='floor.floormodel'),
        ),
    ]
