# Generated by Django 4.1.7 on 2023-03-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0001_initial'),
        ('elevator', '0003_alter_elevatormodel_currentfloor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevatormodel',
            name='requestList',
            field=models.ManyToManyField(blank=True, related_name='requestListFloorModel', to='floor.floormodel'),
        ),
    ]
