# Generated by Django 4.1.7 on 2023-03-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0004_alter_elevatormodel_requestlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevatormodel',
            name='moving',
            field=models.BooleanField(default=True),
        ),
    ]
