# Generated by Django 4.1.7 on 2023-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='user',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
